/**
 * Where every decor piece lands inside a room, as JSON — HC-P1-S4.
 *
 * DEC-009 keeps the canvas out of CI, and the machines this project is built
 * on have no GPU, so nobody can screenshot the Pixi scene on demand. What can
 * be shown on any machine is the arithmetic that decides the scene: this
 * script asks the *shipped* modules — `decorArt.ts` for the anchor, scale and
 * draw order, `layout.ts` for the anchor grid, the asset manifest for the
 * declared sprite size — where each piece's box ends up, and prints it.
 *
 * That JSON is what `tools/art/decor_preview.py` composes into a picture, so
 * the picture cannot drift from the code: it has no geometry of its own.
 *
 * Run: node --experimental-strip-types tools/art/decor-layout.ts [defId ...]
 *      node --experimental-strip-types tools/art/decor-layout.ts --out FILE
 */
import fs from 'node:fs';
import { BLOCK_W, BLOCK_H, anchorToLocalPx } from '../../src/render/layout.ts';
import {
  decorArtSpec, decorDrawSize, compareDecorDraw, decorBox, clampDecorBox,
} from '../../src/render/decorArt.ts';
import type { DecorOrderable } from '../../src/render/decorArt.ts';
import {
  firstFreeAnchor, anchorBoundsFor, anchorKey, anchorReachFor,
} from '../../src/core/systems/decorPlacement.ts';
import { loadSimData } from '../balance-sim/load-data.ts';

interface ManifestEntry { key: string; file: string; width: number; height: number }
const manifest = JSON.parse(fs.readFileSync('public/assets/manifest.json', 'utf8')) as {
  entries: ManifestEntry[];
};
const entryFor = (key: string): ManifestEntry | undefined => manifest.entries.find((e) => e.key === key);

const args = process.argv.slice(2);
const outFlag = args.indexOf('--out');
const outFile = outFlag >= 0 ? args[outFlag + 1] : null;
if (outFlag >= 0) args.splice(outFlag, 2);
const roomFlag = args.indexOf('--room');
const roomDefId = roomFlag >= 0 ? (args[roomFlag + 1] ?? 'economy') : 'economy';
if (roomFlag >= 0) args.splice(roomFlag, 2);

const data = loadSimData();
const room = data.rooms.find((r) => r.id === roomDefId);
if (!room) throw new Error(`no room "${roomDefId}" in data/rooms.json`);

/** Default cast: the ten pieces ART-1 delivered (docs/ART-1_METADATA.md). */
const DEFAULT_PIECES = [
  'wallpaper_plain', 'flooring_concrete', 'wallArt_poster', 'lighting_lamp', 'rug_mat',
  'bed_single', 'seating_armchair', 'table_deskWood', 'plant_fern', 'luxury_aquarium',
];
const defIds = args.length > 0 ? args : DEFAULT_PIECES;

// Anchors exactly as PLACE_DECOR hands them out: one room, one taken-set,
// pieces added in order. Nothing here invents a position.
const bounds = anchorBoundsFor(data, room.id);
const taken = new Set<string>();
const placed: Array<DecorOrderable & { defId: string; assetKey: string; localX: number }> = [];
for (const defId of defIds) {
  const def = data.decor.find((d) => d.id === defId);
  if (!def) throw new Error(`no decor "${defId}" in data/decor.json`);
  const anchor = firstFreeAnchor(bounds, def.slotType, taken, anchorReachFor(data, defId));
  taken.add(anchorKey(anchor.x, anchor.y));
  placed.push({
    id: `${defId}#1`, defId, assetKey: def.assetKey, category: def.category,
    slotType: def.slotType, localX: anchor.x, localY: anchor.y, zBias: 0,
  });
}

const roomEntry = entryFor(`room.${room.id}.base`);
const layoutRoomW = room.blocks.w * BLOCK_W;
const layoutRoomH = room.blocks.h * BLOCK_H;
const layout = {
  note: 'Generated by tools/art/decor-layout.ts from the shipped render modules. Do not hand-edit.',
  room: {
    defId: room.id,
    file: roomEntry?.file ?? `rooms/${room.id}_base.png`,
    width: layoutRoomW,
    height: layoutRoomH,
  },
  pieces: [...placed].sort(compareDecorDraw).map((piece) => {
    const spec = decorArtSpec(piece.category, piece.slotType);
    const entry = entryFor(piece.assetKey);
    const size = decorDrawSize(entry?.width ?? 0, entry?.height ?? 0);
    const at = anchorToLocalPx(piece.localX, piece.localY);
    const raw = decorBox(at, size, spec);
    const box = clampDecorBox(raw, layoutRoomW, layoutRoomH);
    return {
      defId: piece.defId,
      assetKey: piece.assetKey,
      file: entry?.file ?? null,
      band: spec.band,
      anchor: { x: spec.anchorX, y: spec.anchorY },
      anchorPx: { x: at.x, y: at.y },
      size: { w: size.w, h: size.h },
      // The box the sprite covers in room-local pixels — what a screenshot
      // would show, and what the preview composes. `clamped` flags a piece the
      // renderer had to pull back inside its room (an anchor from a pre-S4
      // save); a piece placed since is never clamped.
      box,
      clamped: box.left !== raw.left || box.top !== raw.top,
    };
  }),
};

const json = JSON.stringify(layout, null, 2) + '\n';
if (outFile) {
  fs.mkdirSync(outFile.replace(/\/[^/]+$/, ''), { recursive: true });
  fs.writeFileSync(outFile, json);
  console.info(`${outFile} -> ${layout.pieces.length} pieces in a ${layout.room.width}x${layout.room.height} ${room.id}`);
  for (const p of layout.pieces) {
    const inside = p.box.left >= 0 && p.box.top >= 0
      && p.box.left + p.box.w <= layout.room.width && p.box.top + p.box.h <= layout.room.height;
    console.info(
      `  ${p.band.padEnd(5)} ${p.defId.padEnd(18)} ` +
      `box ${p.box.left.toFixed(1)},${p.box.top.toFixed(1)} ${p.box.w.toFixed(1)}x${p.box.h.toFixed(1)}` +
      `${p.clamped ? '   (clamped back inside)' : ''}${inside ? '' : '   OUTSIDE THE ROOM'}`,
    );
  }
} else {
  console.info(json);
}
